name: wait-for-workflows

on:
  pull_request:

jobs:
  wait-for-workflows:
    runs-on: ubuntu-slim
    timeout-minutes: 15
    steps:
      - uses: int128/wait-for-workflows-action@2afccfd6d7645702a5814a58a812f16b065ee687 # v1.83.0
